// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDZg7qtao6W716t5gyT99RWTBr9BgK3Y',
    appId: '1:910319419656:web:68dacc700cc88ee25bacbd',
    messagingSenderId: '910319419656',
    projectId: 'authentication-98a6d',
    authDomain: 'authentication-98a6d.firebaseapp.com',
    storageBucket: 'authentication-98a6d.firebasestorage.app',
    measurementId: 'G-KQND0RM76E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhoOyqiJZpIigKgghi3Povv86Z1Ej11c',
    appId: '1:910319419656:android:f599cd818c0c20f85bacbd',
    messagingSenderId: '910319419656',
    projectId: 'authentication-98a6d',
    storageBucket: 'authentication-98a6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY0sCYkET9kDISMg_5qMCg2FPMu_xY-sM',
    appId: '1:910319419656:ios:5f5bd847e0b9ac165bacbd',
    messagingSenderId: '910319419656',
    projectId: 'authentication-98a6d',
    storageBucket: 'authentication-98a6d.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY0sCYkET9kDISMg_5qMCg2FPMu_xY-sM',
    appId: '1:910319419656:ios:5f5bd847e0b9ac165bacbd',
    messagingSenderId: '910319419656',
    projectId: 'authentication-98a6d',
    storageBucket: 'authentication-98a6d.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJDZg7qtao6W716t5gyT99RWTBr9BgK3Y',
    appId: '1:910319419656:web:dcf6584b66f72e425bacbd',
    messagingSenderId: '910319419656',
    projectId: 'authentication-98a6d',
    authDomain: 'authentication-98a6d.firebaseapp.com',
    storageBucket: 'authentication-98a6d.firebasestorage.app',
    measurementId: 'G-16QHE8R64T',
  );
}
